### ISSUE TITLE
[Frage] DSGVO?

### ISSUE THREAD

**Issue by akroii** [chopsol/contao-matomo-tracker#1]
Wie sieht eigentlich die rechtliche Situation mit dem Background-Tracking unter Berücksichtigung der DSGVO aus?
Muss man sich hierbei eine Einwilligung über die Cookiebar geholt werden?

**Comment by chopsol** [comment]
Ich bin kein Datenschützer, von daher darf ich hier keine Beratung zu geben.
Dennoch verweise ich gerne auf den Datenschutzbeauftragen des Landes Baden Würtemberg (https://www.baden-wuerttemberg.datenschutz.de/faq-zu-cookies-und-tracking-2/) der - wenn ich das richtig interpretiere - die Nutzung von Matomo ohne Cookie als Legitim ansieht. Basierend auf der Annahme das Contao nur mit Session-Cookies arbeitet und somit eine Wiedererkennung von Nutzern über die Session hinaus nicht ermöglichen, könnte der Einsatz ebenfalls ohne Einwilligung des Benutzers möglich sein. Aber wie so oft: hier scheiden sich die Geister denn wenn selbst die Analyse von Logfiles für statistische Zwecke im Rahmen der DSGVO in Frage gestellt wird, könnte natürlich auch das Background Tracking problematisch sein.
Eine finale Entscheidung für oder gegen den Einsatz muss daher wohl der jeweilige Datenschutzbeauftragte des Website-Betreibers treffen.
