### ISSUE TITLE
Contao 4.13 und PHP 8 Support

### ISSUE THREAD

**Issue by 9teufel** [chopsol/contao-matomo-tracker#2]
Danke für die Erweiterung.

Ist ein Update für PHP 8 geplant?

**Comment by chopsol** [comment]
Geplant war es noch nicht, kann ich aber anpassen. Ich schaue, dass ich das in den nächsten Tagen angehe. Danke für die Anfrage.

**Comment by codesache** [comment]
@chopsol Joachim das wäre mega wenn du es auf PHP 8 / 4.13 anpasst. Ich kann gerne testen!

**Comment by 9teufel** [comment]
@chopsol möchte ganz höflich fragen ob es eventuell schon eine Version für PHP 8 / 4.13 zum testen gibt. Danke!

**Comment by chopsol** [comment]
@9teufel @codesache - die Aktualisierung ist gerade veröffentlicht. Ich freue mich über euer Feedback :-)
