### ISSUE TITLE
IP-Adresse / Standort wird nicht geloggt

### ISSUE THREAD

**Issue by 9teufel** [chopsol/contao-matomo-tracker#4]
In den Einstellungen habe ich "IP an Matomo übergeben" aktiviert. Leider wird nicht die Besucher-IP sondern die Webserver-IP an Matomo gesendet, somit ist auch kein Standort in der Auswertung verfügbar.

Nutze Version 1.0.3 unter Contao 4.13

Binde ich Matomo direkt via JavaScript ein, wird der Standort gespeichert. Deshalb sind die Matomo Einstellungen sicherlich korrekt.

Vielen Dank!

**Comment by chopsol** [comment]
Hast Du den Debug-Modus aktiviert? Dann werden im Contao Systemlog alle Requests an Matomo angezeigt. Schau bitte dort nach, welche IP-Adresse in dem Aufruf steht. Ist dies die IP-Adresse des Servers? In allen Fällen?

**Comment by 9teufel** [comment]
Danke!

Habe Debug aktiviert, dort sehe ich aber keine IP.

`Background-Tracking: https://matomo.xxx.com/matomo.php?idsite=2&rec=1&apiv=1&r=869561&_idts=1693896781&_idvc=0&gt_ms=289&cid=eda6dbb784bb4d75&url=https%3A%2F%2Fdev.xxx.com%2Fde%2Fdienstleistungen&urlref=https%3A%2F%2Fdev.xxx.com%2Fde%2Floesungen&pv_id=01bf5b&ua=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10.15%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F114.0&lang=en%2Cde%3Bq%3D0.7%2Cen-US%3Bq%3D0.3
`

Was bewirkt die Einstellung "Token für Matomo" in der Seitenstruktur? Nicht dass es damit zusammenhängt…

**Comment by chopsol** [comment]
Die HTTP-API von Matomo lässt die Übergabe einer fremden IP-Adresse nur zu, wenn ein Token eines Matomo-Nutzers mit Schreibrechten für die Webseite übergeben wird. Wenn Du keinen Token hinterlegt hast, wird die IP-Adresse nicht übergeben.
Das Gleiche gilt für die Übergabe von Geo IP-Daten, die ggf. auf dem Webserver bereitgestellt werden. Auch diese werden nur in Verbindung mit einem Token übergeben.

**Comment by 9teufel** [comment]
OK, das war mir nicht ganz klar – danke. Mit Token funktioniert's wie gewünscht.

**Comment by chopsol** [comment]
Eine Dokumentation wäre hilfreich :-) Steht auf meiner ToDo-Liste.
